# Generated by Django 2.1.13 on 2019-12-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='sumaary',
            new_name='summary',
        ),
    ]
